.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CLOUDAPP" "1" "December 2012" "" ""
.
.SH "NAME"
\fBcloudapp\fR \- all the pleasures of cloudapp in a cli
.
.SH "SYNOPSIS"
\fBcloudapp bookmark\fR [\fB\-\-direct\fR] \fIurl\fR [\fIurl\fR\.\.\.]
.
.br
\fBcloudapp upload\fR [\fB\-\-direct\fR] \fIfile\fR [\fIfile\fR\.\.\.]
.
.SH "DESCRIPTION"
Upload a file or share a bookmark with CloudApp\. The drop\'s share link will be printed to standard output\. Account credentials are stored in \fB~/\.netrc\fR\.
.
.SH "OPTIONS"
.
.TP
\fB\-d\fR, \fB\-\-direct\fR
Print the drop\'s direct link after creation\. The direct link is suitable for use in places that expect a link to a file like an HTML IMG tag\.
.
.SH "EXIT STATUS"
cloudapp may return one of several error codes if it encouters problems\.
.
.IP "\(bu" 4
\fB0\fR Success
.
.IP "\(bu" 4
\fB1\fR File exceeds the limits of the account\'s plan
.
.IP "\(bu" 4
\fB9\fR Some horrible, unexpected thing has happened
.
.IP "" 0
.
.SH "FILES"
.
.TP
\fB$HOME/\.netrc\fR
Store account authentication token
.
.SH "EXAMPLE"
Upload a file:
.
.IP "" 4
.
.nf

$ cloudapp upload screenshot\.png
http://cl\.ly/abc123
.
.fi
.
.IP "" 0
.
.P
Upload several files:
.
.IP "" 4
.
.nf

$ cloudapp upload *\.png
http://cl\.ly/abc123
http://cl\.ly/def456
http://cl\.ly/ghi789
.
.fi
.
.IP "" 0
.
.P
Copy the drop\'s share link to the clipboard on OS X:
.
.IP "" 4
.
.nf

$ cloudapp upload screenshot\.png | pbcopy
.
.fi
.
.IP "" 0
.
.P
Bookmark a URL:
.
.IP "" 4
.
.nf

$ cloudapp bookmark http://getcloudapp\.com
http://cl\.ly/abc123
.
.fi
.
.IP "" 0
.
.P
Print the drop\'s direct link:
.
.IP "" 4
.
.nf

$ cloudapp upload \-\-direct screenshot\.png
http://cl\.ly/abc123/screenshot\.png
.
.fi
.
.IP "" 0
.
.SH "SEE ALSO"
\fBftp\fR(1)
