.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CLOUDAPP" "1" "May 2012" "" ""
.
.SH "NAME"
\fBcloudapp\fR \- All the pleasures of CloudApp now at your terminal
.
.SH "SYNOPSIS"
\fBcloudapp\fR [\fIglobal\fR] \fBlist\fR
.
.br
\fBcloudapp\fR [\fIglobal\fR] \fBdetails\fR \fIhref\fR [\fIhref\fR\.\.\.]
.
.br
\fBcloudapp\fR [\fIglobal\fR] \fBbookmark\fR [\fIoptions\fR] \fIurl\fR [\fIurl\fR\.\.\.]
.
.br
\fBcloudapp\fR [\fIglobal\fR] \fBupload\fR [\fIoptions\fR] \fIfile\fR [\fIfile\fR\.\.\.]
.
.br
\fBcloudapp\fR [\fIglobal\fR] \fBupdate\fR [\fIoptions\fR] \fIhref\fR [\fIhref\fR\.\.\.]
.
.br
\fBcloudapp\fR [\fIglobal\fR] \fBtrash\fR \fIhref\fR [\fIhref\fR\.\.\.]
.
.br
\fBcloudapp\fR [\fIglobal\fR] \fBrestore\fR \fIhref\fR [\fIhref\fR\.\.\.]
.
.br
\fBcloudapp\fR [\fIglobal\fR] \fBdelete\fR \fIhref\fR [\fIhref\fR\.\.\.]
.
.SH "DESCRIPTION"
\fBcloudapp\fR is a simple, Unix\-friendly tool for CloudApp meant to augment the Mac and Web apps\. Sometimes it\'s more convenient to share without leaving the terminal and other times it\'s the only tool available\.
.
.SH "GLOBAL OPTIONS"
.
.TP
\fB\-f\fR \fIpretty,csv\fR, \fB\-\-format\fR=\fIpretty,csv\fR
Output using either \fBpretty\fR or \fBcsv\fR format\. (Default: \fBpretty\fR when output to a terminal and \fBcsv\fR when output is piped to another program\.)
.
.SH "COMMANDS"
.
.TP
\fB\-\-bookmark\fR=\fIurl\fR
Update the drop converting it into a bookmark to \fIurl\fR\.
.
.TP
\fBbookmark\fR [\fB\-\-private\fR] [\fB\-\-public\fR] \fIurl\fR [\fIurl\fR\.\.\.]
Create a new bookmark to each \fIurl\fR and print the share links\.
.
.TP
\fBdelete\fR \fIhref\fR [\fIhref\fR\.\.\.]
Permanently delete each drop at \fIhref\fR\.
.
.TP
\fBdetails\fR \fIhref\fR [\fIhref\fR\.\.\.]
View the details of each drop at \fIhref\fR\.
.
.TP
\fBlist\fR [\fB\-\-count\fR=\fIcount\fR] [\fB\-\-filter\fR=\fIactive,trash,all\fR]
List the newest \fIcount\fR of \fIfilter\fR drops\. The default is to list \fB20 active\fR drops\.
.
.TP
\fBrestore\fR \fIhref\fR [\fIhref\fR\.\.\.]
Restore each drop at \fIhref\fR from the trash\.
.
.TP
\fBtrash\fR \fIhref\fR [\fIhref\fR\.\.\.]
Send each drop at \fIhref\fR to the trash\.
.
.TP
\fBupdate\fR [\fB\-\-name\fR=\fIname\fR] [\fB\-\-private\fR] [\fB\-\-public\fR] [\fB\-\-bookmark\fR=\fIurl\fR] [\fB\-\-file\fR=\fIfile\fR] \fIhref\fR [\fIhref\fR\.\.\.]
Update the name, privacy, bookmark link, or file of each drop at \fIhref\fR\.
.
.TP
\fBupload\fR [\fB\-\-private\fR] [\fB\-\-public\fR] \fIfile\fR [\fIfile\fR\.\.\.]
Upload each \fIfile\fR and print the share links\.
.
.SH "COMMAND OPTIONS"
.
.TP
\fB\-\-bookmark\fR=\fIurl\fR
Update the drop converting it into a bookmark to \fIurl\fR\.
.
.TP
\fB\-\-file\fR=\fIfile\fR
Update the drop converting it into a file and replacing its content with \fIfile\fR\.
.
.TP
\fB\-\-filter\fR=\fIactive,trash,all\fR
Show \fIfilter\fR drops\. (Default: \fBactive\fR)
.
.TP
\fB\-n\fR \fIcount\fR, \fB\-\-count\fR=\fIcount\fR
Display \fIcount\fR drops\. (Default: \fB20\fR)
.
.TP
\fB\-\-name\fR=\fIname\fR
Update the drop\'s name to \fIname\fR\.
.
.TP
\fB\-\-private\fR
Use a private (long) link for the drop\.
.
.TP
\fB\-\-public\fR
Use a public (short) link for the drop\.
.
.SH "REQUIREMENTS"
\fBcloudapp\fR requires Ruby 1\.9\.2 or greater\.
.
.SH "EXAMPLES"
List the newest drops:
.
.IP "" 4
.
.nf

$ cloudapp list
Name                    Views  Href
favicon\.ico             1      http://api\.getcloudapp\.com/\.\.\.
The Hitchhiker\'s Guide  0      http://api\.getcloudapp\.com/\.\.\.
CloudApp 1\.5 Released   5      http://api\.getcloudapp\.com/\.\.\.
Cover\.jpeg              23     http://api\.getcloudapp\.com/\.\.\.
Chapter 1\.md            8      http://api\.getcloudapp\.com/\.\.\.
CloudApp                3      http://api\.getcloudapp\.com/\.\.\.
  \.\.\.
.
.fi
.
.IP "" 0
.
.P
List the 5 newest drops:
.
.IP "" 4
.
.nf

$ cloudapp list \-\-count=5
Name                    Views  Href
favicon\.ico             1      http://api\.getcloudapp\.com/\.\.\.
The Hitchhiker\'s Guide  0      http://api\.getcloudapp\.com/\.\.\.
CloudApp 1\.5 Released   5      http://api\.getcloudapp\.com/\.\.\.
Cover\.jpeg              23     http://api\.getcloudapp\.com/\.\.\.
Chapter 1\.md            8      http://api\.getcloudapp\.com/\.\.\.
.
.fi
.
.IP "" 0
.
.P
List newest, deleted drops:
.
.IP "" 4
.
.nf

$ cloudapp list \-\-filter=trash
Name       Views  Href
Delete Me  0      http://api\.getcloudapp\.com/\.\.\.
  \.\.\.
.
.fi
.
.IP "" 0
.
.P
List newest 5 drops in CSV format:
.
.IP "" 4
.
.nf

$ cloudapp \-\-format=csv list \-\-count=5
Name,Href,Share,Views
favicon\.ico,http://api\.getcloudapp\.com/\.\.\.,http://cl\.ly/0P28\.\.\.,3
The Hitchhiker\'s Guide to the Galaxy,http://api\.getcloudapp\.com/\.\.\.,http://cl\.ly/3I28\.\.\.,4
2011\-05\-03\-cloudapp\-1\.5\-released\.md,http://api\.getcloudapp\.com/\.\.\.,http://cl\.ly/0s1o\.\.\.,4
Cover\.jpeg,http://api\.getcloudapp\.com/\.\.\.,http://cl\.ly/1x20\.\.\.,1
Chapter 1\.md,http://api\.getcloudapp\.com/\.\.\.,http://cl\.ly/3U3d\.\.\.,7
.
.fi
.
.IP "" 0
.
.P
View the details of a drop by its \fBhref\fR:
.
.IP "" 4
.
.nf

$ cloudapp details http://api\.getcloudapp\.com/drops/12345
Details
  Name:     Cover\.jpeg
  Views:    23
  Privacy:  Private

Links
  Share:    http://cl\.ly/1x200A0m3v101d1n2O1u
  Embed:    http://cl\.ly/1x200A0m3v101d1n2O1u/Cover\.jpeg
  Download: http://cl\.ly/1x200A0m3v101d1n2O1u/download/Cover\.jpeg
  Href:     http://api\.getcloudapp\.com/drops/13949858
.
.fi
.
.IP "" 0
.
.P
View the details of a drop in CSV format:
.
.IP "" 4
.
.nf

$ cloudapp \-\-format=csv details http://api\.getcloudapp\.com/drops/12345
Name,Created,Privacy,Share,Embed,Download
Cover\.jpg,2012\-01\-12T20:44:58Z,private,http://cl\.ly/1x20\.\.\.,http://cl\.ly/1x20\.\.\.,http://cl\.ly/1x20\.\.\.
.
.fi
.
.IP "" 0
.
.P
Share a new bookmark to \fBhttp://douglasadams\.com\fR:
.
.IP "" 4
.
.nf

$ cloudapp bookmark http://douglasadams\.com
Bookmarking http://douglasadams\.com\.\.\. http://cl\.ly/1y0j403g3D0c0X1G0R3m
.
.fi
.
.IP "" 0
.
.P
Share the file \fBscreenshot\.png\fR:
.
.IP "" 4
.
.nf

$ cloudapp upload screenshot\.png
Uploading screenshot\.png\.\.\. http://cl\.ly/040u2o3X1w0z1z3n2T04
.
.fi
.
.IP "" 0
.
.P
Share a new bookmark or file and copy the URL to the clipboard (OS X):
.
.IP "" 4
.
.nf

$ cloudapp bookmark http://douglasadams\.com | pbcopy
$ cloudapp upload screenshot\.png | pbcopy
.
.fi
.
.IP "" 0
.
.P
Share a new bookmark and output only the URL:
.
.IP "" 4
.
.nf

$ cloudapp \-\-format=csv bookmark http://douglasadams\.com
http://cl\.ly/1y0j403g3D0c0X1G0R3m
.
.fi
.
.IP "" 0
.
.P
Update a drop with a new name and privacy:
.
.IP "" 4
.
.nf

$ cloudapp update \-\-public \e
                  \-\-name=\'The Late, Great Douglas Adams\' \e
                  http://api\.getcloudapp\.com/drops/12345
Updating\.\.\. http://cl\.ly/abc123
.
.fi
.
.IP "" 0
.
.P
Update a drop with a new bookmark URL:
.
.IP "" 4
.
.nf

$ cloudapp update \-\-bookmark=http://douglasadams\.com \e
                  http://api\.getcloudapp\.com/drops/12345
Updating\.\.\. http://cl\.ly/1y0j403g3D0c0X1G0R3m
.
.fi
.
.IP "" 0
.
.P
Update a drop with a new file:
.
.IP "" 4
.
.nf

$ cloudapp update \-\-file=screenshot\.png \e
                  http://api\.getcloudapp\.com/drops/12345
Updating\.\.\. http://cl\.ly/1y0j403g3D0c0X1G0R3m
.
.fi
.
.IP "" 0
.
.P
Trash a drop:
.
.IP "" 4
.
.nf

$ cloudapp trash http://api\.getcloudapp\.com/drops/12345
Trashing http://api\.getcloudapp\.dev/drops/12345\.\.\. done
.
.fi
.
.IP "" 0
.
.P
Deleting a drop:
.
.IP "" 4
.
.nf

$ cloudapp trash http://api\.getcloudapp\.com/drops/12345
Delete http://api\.getcloudapp\.dev/drops/12345 forever? (y/n)
yes
Deleting http://api\.getcloudapp\.dev/drops/12345\.\.\. done
.
.fi
.
.IP "" 0
.
.SH "LICENSE"
\fBcloudapp\fR is distributed under the MIT license \fIhttps://github\.com/cloudapp/cloudapp/blob/master/MIT\-LICENSE\fR\.
